const skills = [
  {name: "javascript", type: "language" },
  {name: "react", type: "front-end"},
  {name: "react-router", type: "front-end"},
  {name: "redux", type: "front-end"},
  {name: "node", type: "back-end"},
  {name: "express", type: "back-end"},
  {name: "webpack", type: "front-end"},
  {name: "mongodb", type: "database"},
  {name: "mongoose", type: "database"},
  {name: "auth0", type: "auth"},
  {name: "jwt", type: "auth"},
  {name: "bcrypt", type: "auth"},
  {name: "css/scss", type: "css-framework"},
  {name: "bulma", type: "css-framework"},
  {name: "semantic-ui", type: "css-framework"},
  {name: "socket.io", type: "js-lib"},
  {name: "d3", type: "dataviz"},
  {name: "recharts", type: "dataviz"},
  {name: "bootstrap", type: "css-framework", hover: "In many older projects"},
  {name: "jquery", type: "js-lib", hover: "In many older projects"},
  {name: "sql", type: "database", hover: "MySQL, Oracle SQL, PL/SQL (School), PostgreSQL (10-week internship)" },
  {name: "php", type: "language", hover: "At school and during a 10-week internship"},
  {name: "symfony 2/3", type: "full-framework", hover: "Learned from OpenClassrooms and used during a 10-week intership"},
  {name: "python", type: "language", hover: "Learned from OpenClassrooms and Dataquest and used for quick data parsing"},
  {name: "django", type: "full-framework", hover: "Learned from DjangoGirls out of curiosity"},
  {name: "java", type: "language", hover: "Learned at school"},
  {name: "design patterns", type: "other", hover: "Head First Design Patterns is an amazing book!"},
  {name: "uml", type: "other", hover: "Learned at school"}
];

export default skills;